# Generated by Django 5.2.17 on 2026-09-14 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('java', 'Java'), ('assembly', 'Assembly'), ('other', 'Other')], default='other', max_length=20)),
                ('technologies', models.CharField(max_length=255)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
